apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-staging
  namespace: argocd
  finalizers: [ "resources-finalizer.argocd.argoproj.io" ]
  labels:
    kargo.akuity.io/stage: staging
spec:
  project: default
  sources:
    - repoURL: https://github.com/gaytriparmar22oct/Platform_Engineering.git
      targetRevision: main
      path: ecommerce-charts/cart
      helm:
        releaseName: cart
        valueFiles:
          - $values/ecommerce-gitops/envs/staging/cart/values.yaml
    - repoURL: https://github.com/gaytriparmar22oct/Platform_Engineering.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-staging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
