# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "azure/dev/live\\azure\\dev\\kubernetes-cluster/terraform.tfstate"
    resource_group_name  = "GaytriRG"
    storage_account_name = "sttfidpq92b45"
    use_azuread_auth     = true
  }
}
