---
# Source: cart/templates/all.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  labels:
    helm.sh/chart: cart-0.1.0
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: ecommerce
---
# Source: cart/templates/all.yaml
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    helm.sh/chart: cart-0.1.0
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart
---
# Source: cart/templates/all.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    helm.sh/chart: cart-0.1.0
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: ecommerce
spec:
  revisionHistoryLimit: 5
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
      app.kubernetes.io/instance: cart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cart
        app.kubernetes.io/instance: cart
      annotations:
    spec:
      serviceAccountName: cart
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        workload: apps
      containers:
        - name: cart
          image: "ecommerce/cart:0.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
---
# Source: cart/templates/all.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart
  labels:
    helm.sh/chart: cart-0.1.0
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: ecommerce
    release: "prometheus-stack"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
      app.kubernetes.io/instance: cart
  endpoints:
    - port: "http"
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
